### ISSUE TITLE
sensible default for environmentName

### ISSUE THREAD

**Issue by lusitania** [dbtlr/php-airbrake#23]
Please change the default of this field in Configuration to a value that is both safe and meaningful. 'production' is neither in general. It is only appropriate under certain conditions the implementing party may decide. In short: it makes for poor default value.

Instead I'd suggest choosing a value like 'uninitialised' that tells the user there is need for customisation.

I'm bringing this up here because I've seen 3rd party tools using php-airbrake without giving proper defaults a thought, too, and I end up patching a chain of infrastructure components (which breaks update scenarios).

Thanks for listening

**Comment by dbtlr** [comment]
I'm closing this as I tend to disagree about it being a poor default choice. Uninitialized implies that you MUST change it to get value. If you want to customize this, the option is available.
