### ISSUE TITLE
Hard dependency of PHPUnit 3.7.28

### ISSUE THREAD

**Issue by mtymek** [dbtlr/php-airbrake#38]
php-airbrake has now hard dependency on PHPUnit v3.7.28. My project requires PHPUnit 4.5, so I cannot `composer update` anymore.

**Comment by dbtlr** [comment]
Good catch. I'll remove the version dependecy on the dev libraries.

**Comment by dbtlr** [comment]
I've updated to 1.1.1, which should solve this issue. Let me know if you're still having problems.

**Comment by mtymek** [comment]
Works fine now - thanks!
