### ISSUE TITLE
Return created error id

### ISSUE THREAD

**Issue by smichaelsen** [dbtlr/php-airbrake#51]
\Airbrake\Connection->send() returns an XML string with an error id, e.g.:
`<error-id>86432-107416147</error-id>`

But `\Airbrake\Client->notify()` doesn't handle this information an it is lost. It would be helpful to get the error id back to the application, so that the exception page can link to the exception report.

**Comment by dbtlr** [comment]
Hey @smichaelsen,

This implementation of php-airbrake is deprecated. I'd suggest either looking to switch to the official repository: https://github.com/airbrake/phpbrake or, if you'd like to take a crack at fixing this via a pull request, I'll take a look and merge it in.
